### ISSUE TITLE
Feature Request - Ack for Completion with Log

### ISSUE THREAD

**Issue by ajmarroquin** [snowskeleton/ynam#19]
Hey!

I've been using YNAM for a week or so, it's been great so far and super useful. I haven't gotten it to work well with crontab for some reason, but haven't dove deep to investigate and just run it manually a couple times a day when i think about budgeting.

I've had an idea on improvement:

In general it would be great to see some action feedback from the application, most specifically a log and acknowledgement of success. I'd imagine after running `ynam`, you could send an Ack to the console that says `YNAM wrote xx Transactions succesfully.`  

I understand that what data could be presented is dependent on YNABs api giving you feedback, so could even give nicer results but right now you type in `ynam` and just wait for a new line and are unsure if there was success in writing to YNAB without going to look at the budget.

I guess this isn't a problem if you ONLY run headless and via crontab, but if you're running manually it would be nice!

Thanks in advance.

**Comment by snowskeleton** [comment]
I'm glad you've found it useful!
The issue I ran into with cron is that, by default, cron jobs are run as `root`, and ynam is expecting to find things in your home directory. I have the following line in `/etc/crontab`:
```
*/15 *  * * *   snow  ynam
```
You could also use `su` to achieve a similar end.

Re ack: I added a verbosity flag per your request. Give it a try, and lemme know if it doesn't quite work the way you expect.

**Comment by snowskeleton** [comment]
I'll close this issue assuming you have no more concerns. Feel free to open up another issue for more problems.

**Comment by ajmarroquin** [comment]
Hey! just writing back as I was out last week, it seems like this function works well. 

![image](https://user-images.githubusercontent.com/43194782/199237669-315cf37b-3359-4a7d-aceb-8d86bccb8ab2.png)

**Comment by snowskeleton** [comment]
I'm glad you like it!
