### ISSUE TITLE
Budget selection showing incorrect accounts

### ISSUE THREAD

**Issue by bayonhealth** [snowskeleton/ynam#24]
I currently have 3 budgets associated with my account, and once I selected my budget of choice, it showed me the account listings of a different budget. Wondering if this was a bug, I chose a different budget and it produced the correct listing of credit cards I was originally looking for.

Example: Chose Budget #1, but showed me accounts from Budget #2. Started over and chose Budget #2 and it showed me the accounts for Budget #1.

**Comment by snowskeleton** [comment]
This is quite strange. Thank you for bringing it to my attention! I added another budget to my own account and was able to reproduce the bug. A fix is imminent.
