### ISSUE TITLE
Issue with ynam quick start

### ISSUE THREAD

**Issue by AndrewMcLeod03** [snowskeleton/ynam#27]
Hey,

Really excited about the work you put into these apps!

I'm working on installing ynam and got a snag with the command ynam quickstart. Below is the terminal window with the error .

My  machine is the Libre Le Potato. It's similar to the raspberry Pi.
![ImageYNAM](https://user-images.githubusercontent.com/116534947/214772727-837a4af6-6adb-4d29-a8ba-c20cd30b8313.jpg)

**Comment by snowskeleton** [comment]
You have to install the mintapi module from [here](https://github.com/snowskeleton/mintapi), as noted at the top of the `README`. That should solve your issue.

**Comment by AndrewMcLeod03** [comment]
Appreciate the quick response! I should have said, I have installed mintapi already. Here is proof of install and the error right after.

![image](https://user-images.githubusercontent.com/116534947/214986273-c48e5f07-02e5-4b14-b667-dd84aeea24ce.png)

Am I doing anything wrong? I'm mostly a C# developer, so using curl and pip is new to me. haha

Thank you so much!

**Comment by AndrewMcLeod03** [comment]
OK I'm a little dumb. I just figured it out. I was still trying to install from pip, even though you said to do it manually. My bad...

Also  I was totally calling quickstart wrong. Sorry!! I'm actually visually impaired and just missed the '--' haha.

Well thanks for your help anyway!

**Comment by snowskeleton** [comment]
I owe you a debt of gratitude for bringing this issue to my attention yet again. It was the motivation I needed to update the build system to more correctly manage packages.

**Comment by AndrewMcLeod03** [comment]
Great! I'm glad it was helpful at least.

Thanks for all your hard work!! Would love to help with some of the projects at some point. I'm learning python for a neural networks course, so maybe I can help after obtaining more experience.
